# Generated by Django 5.2.8 on 2026-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='variation',
            constraint=models.UniqueConstraint(fields=('product', 'variation_value'), name='unique_variation_per_product'),
        ),
    ]
